# Generated by Django 3.2.5 on 2022-03-20 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '生活类'), (2, '家庭类'), (3, '爱好类')], verbose_name='博客类型')),
                ('blog_title', models.CharField(max_length=250, unique=True, verbose_name='博客标题')),
                ('blog_text', models.TextField(max_length=2048, verbose_name='博客内容')),
                ('created_date', models.DateTimeField(verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(verbose_name='修改日期')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
