# Generated by Django 3.2.5 on 2022-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0002_auto_20220320_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '个人博客', 'verbose_name_plural': '个人博客'},
        ),
        migrations.AddField(
            model_name='blog',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='lgy_blog.Tag', verbose_name='博客标签'),
        ),
    ]
