# Generated by Django 3.2.5 on 2022-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0003_auto_20220321_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_simple_text',
            field=models.CharField(default='233', max_length=250, verbose_name='博客简介'),
        ),
    ]
