# Generated by Django 3.2.5 on 2022-03-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0004_blog_blog_simple_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(default='blog', to='lgy_blog.Tag', verbose_name='博客标签'),
        ),
    ]
