# Generated by Django 3.2.5 on 2022-03-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0006_alter_blog_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
