# Generated by Django 3.2.5 on 2022-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0007_auto_20220330_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_simple_text',
            field=models.CharField(default=' ', max_length=250, verbose_name='博客简介'),
        ),
    ]
