# Generated by Django 3.2.5 on 2022-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0008_alter_blog_blog_simple_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_simple_text',
            field=models.CharField(help_text='请用简短的写一下本Blog的简述', max_length=250, verbose_name='博客简介'),
        ),
    ]
