# Generated by Django 3.2.5 on 2022-03-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgy_blog', '0009_alter_blog_blog_simple_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_date',), 'verbose_name': '个人博客', 'verbose_name_plural': '个人博客'},
        ),
    ]
